# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Norman Qian
tagline:          'Personal Website'
description:      'Norman Qian'
url:              http://normanqian.com
baseurl:          /

author:
  name:           'Norman Qian'
  url:            https://twitter.com/normanqian

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/elizasviel
